version: '3'
services:

# system-level services
#--------------------------------
  nginx:
    image: nginx
    #image: iotcat/ushio-nginx
    #image: docker.yimian.xyz/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/mnt/etc/usa.yimian.xyz/nginx/:/etc/nginx/"
      - "/mnt/etc/:/mnt/etc/"
      - "/mnt/var/ssl/:/mnt/config/ssl/"
      - "/var/log/nginx/:/var/log/nginx/"
      - "/home/www/:/home/www/"
    #network_mode: "host"
    depends_on:
      - php-fpm
      - frps
      - ushio-proxy
    networks:
      - default
      - php_net
      - frp_net

  dns:
    image: strm/dnsmasq
    #image: docker.yimian.xyz/dnsmasq
    restart: always
    volumes:
      - /mnt/etc/common/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - /mnt/etc/common/dnsmasq/dnsmasq.d/:/etc/dnsmasq.d/
      - /mnt/etc/common/dnsmasq/hosts.conf:/etc/hosts.conf
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
    networks:
      - dns_net

# Database
#----------------------------------
  redis:
    image: redis
    #image: docker.yimian.xyz/redis
    container_name: redis
    restart: always
    volumes:
      - "/var/redis/data/:/data/"
    networks:
      - redis_net


# app-level services
# --------------------------------------
  php-fpm:
    image: crunchgeek/php-fpm:7.3
    #image: docker.yimian.xyz/php-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - "/home/:/home/"
      - "/mnt/:/mnt/"
    networks:
      - php_net
  frps:
    image: snowdreamtech/frps
    #image: docker.yimian.xyz/frps
    container_name: frps
    restart: always
    volumes:
      - "/mnt/etc/common/frp/frps.ini:/etc/frp/frps.ini"
    ports:
      - "4480:4480"
      - "4443:4443"
      - "4477:4477"
      - "4450:4450"
      - "4400-4440:4400-4440"
    networks:
      - frp_net
  monitor:
    #build: https://github.com/iotcat/ushio-monitor.git
    image: iotcat/ushio-monitor
    #image: docker.yimian.xyz/monitor
    container_name: monitor
    restart: always
    command: USER=usa.yimian.xyz
    network_mode: "host"

  ushio-img:
    image: yangxuan8282/typecho
    #image: docker.yimian.xyz/wordpress
  # ports:
 #    - "90:80"
    restart: always
    volumes:
      - "/home/www/img/:/var/www/html/"



  redrange:
    image: yangxuan8282/typecho
    #image: docker.yimian.xyz/wordpress
  # ports:
 #    - "90:80"
    restart: always
    volumes:
      - "/home/www/redrange/:/var/www/html/"

# common apps
# -------------------------------------



# local apps
# ---------------------------------------

  ssl:
    #build: https://github.com/iotcat/ushio-ssl.git
    image: iotcat/ushio-ssl
    #image: docker.yimian.xyz:4450/ssl
    container_name: ssl
    restart: always
    command: ["/bin/bash", "-c", "/acme.sh --install && tail -f /dev/null"]
    #deploy:
    #  restart_policy:
    #    delay: 86400s
    volumes:
      - "/var/log/acme.log:/var/log/acme.log"
      - "/mnt/config/acme.sh/:/root/.acme.sh/"
      - "/mnt/var/ssl/:/mnt/config/ssl/"

  oneindex:
#    image: iotcat/oneindex
#    #image: docker.yimian.xyz:4450/oneindex
#    container_name: oneindex
#    restart: always
#    volumes:
#      - "/mnt/config/oneindex/:/var/www/html/config/"
#    healthcheck:
#      test: /bin/bash /healthcheck.sh
#      interval: 1m
#      timeout: 10s
#      retries: 3
    image: iotcat/oneindex
    container_name: oneindex
    restart: always
    volumes:
      - "/mnt/config/oneindex/:/var/www/html/config/" 
    environment:
      - "REFRESH_TOKEN=0 * * * *"
      - "REFRESH_CACHE=*/10 * * * *"



  v2ray:
    image: v2fly/v2fly-core
    #image: docker.yimian.xyz/v2ray
    container_name: v2ray
    restart: always
    volumes:
      - "/mnt/config/v2ray/usa.yimian.xyz/config.json:/etc/v2ray/config.json"
      - "/var/log/v2ray/usa/:/var/log/v2ray/"

  v-china:
    #image: v2ray/official
    image: v2fly/v2fly-core
    #image: iotcat/v-china2
    #image: docker.yimian.xyz/v-china2
    container_name: v-china
    restart: always
    volumes:
      - "/mnt/config/v2ray/usa.yimian.xyz/v-china.config.json:/etc/v2ray/config.json"
   #  - "/mnt/config/ajiasu/ajiasu.conf:/etc/ajiasu.conf"
      - "/var/log/v2ray/v-china/:/var/log/v2ray/"

  ushio-proxy:
    #build: https://github.com/iotcat/ushio-proxy.git
    image: iotcat/ushio-proxy
    #image: docker.yimian.xyz/proxy
    container_name: ushio-proxy
    restart: always

    
# networks setting
# ------------------------------------
networks:
  default:

  dns_net:

  redis_net:

  php_net:

  frp_net:

