version: '3'
services:

# system-level services
#--------------------------------


  nginx:
    #image: iotcat/ushio-nginx
    image: docker.yimian.xyz:5000/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/mnt/etc/home.yimian.xyz/nginx/:/etc/nginx/"
      - "/mnt/etc/:/mnt/etc/"
      - "/mnt/var/ssl/:/mnt/config/ssl/"
      - "/var/log/nginx/:/var/log/nginx/"
      - "/home/:/home/"
    #network_mode: "host"
    #command: sh /ip.sh & nginx -g daemon off;
    depends_on:
      - registry
      - php-fpm
      - v2ray
 





# Database
#----------------------------------

# app-level services
# --------------------------------------
  monitor:
    #build: https://github.com/iotcat/ushio-monitor.git
    #image: iotcat/ushio-monitor
    image: docker.yimian.xyz:5000/monitor
    container_name: monitor
    restart: always
    command: USER=home.yimian.xyz
    network_mode: "host"
    depends_on:
      - registry

  php-fpm:
    #image: crunchgeek/php-fpm:7.3
    image: docker.yimian.xyz:5000/php-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - "/home/:/home/"
      - "/mnt/:/mnt/"
    depends_on:
      - registry



  frpc:
    #image: snowdreamtech/frpc
    image: docker.yimian.xyz:5000/frpc
    container_name: frpc
    restart: always
    volumes:
      - "/mnt/etc/common/frp/frpc.ini.home:/etc/frp/frpc.ini"
    network_mode: "host"
    depends_on:
      - registry

# common apps
# -------------------------------------




# local apps
# ---------------------------------------
  
  registry:
    image: docker.yimian.xyz:5000/registry
    container_name: registry
    restart: always
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/yimian.xyz.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/yimian.xyz.key
    ports:
      - 5000:5000
    volumes:
      - "/mnt/var/ssl/yimian.xyz:/certs"
      - "/var/docker:/var/lib/registry"



  v2ray:
    #image: v2ray/official
    image: docker.yimian.xyz:5000/v2ray
    container_name: v2ray
    restart: always
    volumes:
      - "/mnt/config/v2ray/config.json.china:/etc/v2ray/config.json"
      - "/var/log/v2ray/:/var/log/v2ray/"
    depends_on:
      - registry




# networks setting
# ------------------------------------
networks:
  default:

